### ISSUE TITLE
i's are hard to read

### ISSUE THREAD

**Issue by wikimatze** [padrino/padrino-web-new#29]
![is-hard-to-read](https://cloud.githubusercontent.com/assets/264708/13996401/cc88aa7c-f12d-11e5-9ef0-2e9507d16a9b.png)

@angeloashmore can we simply change the font and/or font-weight?

**Comment by angeloashmore** [comment]
These are called typographic ligatures (see [Wikipedia article](https://en.wikipedia.org/wiki/Typographic_ligature)) and are enabled by default (see [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures)). Ironically, one of the reasons for their existence is to increase readability at smaller font sizes.

**With ligatures**

> <img width="116" alt="screen shot 2016-03-24 at 12 12 34 pm" src="https://cloud.githubusercontent.com/assets/8601064/14032870/dfc26e66-f1b9-11e5-93c2-e238e73fc8e9.png">

**Without ligatures**

> <img width="117" alt="screen shot 2016-03-24 at 12 12 17 pm" src="https://cloud.githubusercontent.com/assets/8601064/14032887/fdf19f74-f1b9-11e5-9b04-746cf8845ca7.png">

It can be disabled explicitly, but I think they should stay.

If you decide you want to disable them, you would just need to add the following to the `body` styles in `_base/_base.scss`:

``` scss
body {
  // ...
  -webkit-font-variant-ligatures: no-common-ligatures;
  font-variant-ligatures: no-common-ligatures;
  // ...
}
```
